DB_URL=mysql://root:fJzOLyUrWGLGGMzDXreJVTDIiiiyIeve@mysql-vvbk.railway.internal:3306/railway
DB_USER=root
DB_PASSWORD=fJzOLyUrWGLGGMzDXreJVTDIiiiyIeve



spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.username=bikashkumarsau0012@gmail.com
spring.mail.password=qwertyuiopasdfg
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

rupee.sign=${RUPEE_SIGN:\u20B9}
server.port=8080
