spring.datasource.url=jdbc:mysql://ballast.proxy.rlwy.net:11043/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.username=root
spring.datasource.password=scIaiAxPxRuXXibiHvIhebMDJZlEMfbr

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.username=bikashkumarsau0012@gmail.com
spring.mail.password=qwertyuiopasdfgh
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

rupee.sign=${RUPEE_SIGN:&#8377;}

server.port=${PORT:8080}
